// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: charges.sql

package repository

import (
	"context"
	"database/sql"
)

const createCharge = `-- name: CreateCharge :exec
INSERT INTO charges (
  id,
  reservation_id,
  user_id,
  amount,
  status,
  charged_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
`

type CreateChargeParams struct {
	ID            string        `json:"id"`
	ReservationID string        `json:"reservation_id"`
	UserID        string        `json:"user_id"`
	Amount        uint32        `json:"amount"`
	Status        ChargesStatus `json:"status"`
	ChargedAt     sql.NullTime  `json:"charged_at"`
}

func (q *Queries) CreateCharge(ctx context.Context, db DBTX, arg CreateChargeParams) error {
	_, err := db.ExecContext(ctx, createCharge,
		arg.ID,
		arg.ReservationID,
		arg.UserID,
		arg.Amount,
		arg.Status,
		arg.ChargedAt,
	)
	return err
}

const existsChargeByReservationIDAndUserID = `-- name: ExistsChargeByReservationIDAndUserID :one
SELECT EXISTS(
  SELECT 1
  FROM charges
  WHERE reservation_id = ?
    AND user_id = ?
)
`

type ExistsChargeByReservationIDAndUserIDParams struct {
	ReservationID string `json:"reservation_id"`
	UserID        string `json:"user_id"`
}

func (q *Queries) ExistsChargeByReservationIDAndUserID(ctx context.Context, db DBTX, arg ExistsChargeByReservationIDAndUserIDParams) (bool, error) {
	row := db.QueryRowContext(ctx, existsChargeByReservationIDAndUserID, arg.ReservationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
