// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type UsersRole string

const (
	UsersRoleGeneral    UsersRole = "general"
	UsersRoleAdmin      UsersRole = "admin"
	UsersRoleBetaTester UsersRole = "beta_tester"
)

func (e *UsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRole(s)
	case string:
		*e = UsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRole: %T", src)
	}
	return nil
}

type NullUsersRole struct {
	UsersRole UsersRole `json:"users_role"`
	Valid     bool      `json:"valid"` // Valid is true if UsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRole), nil
}

func (e UsersRole) Valid() bool {
	switch e {
	case UsersRoleGeneral,
		UsersRoleAdmin,
		UsersRoleBetaTester:
		return true
	}
	return false
}

type UsersStatus string

const (
	UsersStatusActive   UsersStatus = "active"
	UsersStatusInactive UsersStatus = "inactive"
	UsersStatusBanned   UsersStatus = "banned"
)

func (e *UsersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersStatus(s)
	case string:
		*e = UsersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersStatus: %T", src)
	}
	return nil
}

type NullUsersStatus struct {
	UsersStatus UsersStatus `json:"users_status"`
	Valid       bool        `json:"valid"` // Valid is true if UsersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UsersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersStatus), nil
}

func (e UsersStatus) Valid() bool {
	switch e {
	case UsersStatusActive,
		UsersStatusInactive,
		UsersStatusBanned:
		return true
	}
	return false
}

type CategoryMaster struct {
	// カテゴリID
	ID uint32 `json:"id"`
	// カテゴリ名
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type DiscountMaster struct {
	// 割引ID
	ID uint32 `json:"id"`
	// 割引キャンペーン名
	Name string `json:"name"`
	// 割引率（%）
	Rate      int32     `json:"rate"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Product struct {
	// 商品ID
	ID uint32 `json:"id"`
	// 商品名
	Name string `json:"name"`
	// 商品説明
	Description sql.NullString `json:"description"`
	// 税込価格
	Price string `json:"price"`
	// カテゴリID
	CategoryID uint32 `json:"category_id"`
	// 割引ID（NULL可）
	DiscountID sql.NullInt32 `json:"discount_id"`
	// VIP限定フラグ
	VipOnly   bool      `json:"vip_only"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ProductImage struct {
	// 画像ID
	ID int32 `json:"id"`
	// 商品ID
	ProductID uint32 `json:"product_id"`
	// 商品画像URL
	ImageUrl string `json:"image_url"`
	// メイン画像かどうか
	IsMain    sql.NullBool `json:"is_main"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type ProductRating struct {
	// 評価ID
	ID int32 `json:"id"`
	// 商品ID
	ProductID uint32 `json:"product_id"`
	// 評価を行ったユーザーID
	UserID string `json:"user_id"`
	// 評価（1〜5）
	Rate int32 `json:"rate"`
	// 評価日時
	RatedAt   time.Time `json:"rated_at"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ProductStock struct {
	// 商品ID
	ProductID uint32 `json:"product_id"`
	// 在庫数
	StockQuantity uint32    `json:"stock_quantity"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type User struct {
	// ユーザーID
	ID string `json:"id"`
	// ユーザー名
	Username sql.NullString `json:"username"`
	// ユーザーのメールアドレス
	Email sql.NullString `json:"email"`
	// ユーザーの権限
	Role UsersRole `json:"role"`
	// ユーザーのステータス
	Status UsersStatus `json:"status"`
	// 最終ログイン日時
	LastLoginAt time.Time `json:"last_login_at"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
