// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) error
	GetUserByUid(ctx context.Context, db DBTX, uid string) (GetUserByUidRow, error)
}

var _ Querier = (*Queries)(nil)
