// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) error
	GetCreditCardsByUserId(ctx context.Context, db DBTX, uid string) ([]GetCreditCardsByUserIdRow, error)
	GetProductByID(ctx context.Context, db DBTX, productID uint32) (GetProductByIDRow, error)
	GetProductsByIDs(ctx context.Context, db DBTX, productIds []uint32) ([]GetProductsByIDsRow, error)
	GetUserByUid(ctx context.Context, db DBTX, uid string) (GetUserByUidRow, error)
}

var _ Querier = (*Queries)(nil)
